K12WidgetDemo/DancingGoatMvc/Models/Coffees/CoffeeFilterViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

using CMS.DataEngine;
using CMS.Helpers;

using DancingGoat.Repositories.Filters;

namespace DancingGoat.Models.Coffees
{
    public class CoffeeFilterViewModel : IRepositoryFilter
    {
        public bool OnlyDecaf { get; set; }


        [UIHint("CoffeeProductFilter")]
        public CoffeeProductFilterCheckboxViewModel[] ProcessingTypes { get; set; }


        public void Load()
        {
            ProcessingTypes = GetCoffeeProcessingTypes()
               .Select(GetProductFilterCheckboxViewModel)
               .ToArray();
        }


        public WhereCondition GetWhereCondition()
        {
            var decafWhereCondition = GetDecafWhereCondition();
            var processingTypesWhere = GetProcessingTypesWhere();

            return decafWhereCondition.And(processingTypesWhere);
        }


        public string GetCacheKey()
        {
            var serializedProcessingTypes = ProcessingTypes
               .Select(type => string.Format($"{type.Value}:{type.IsChecked}"))
               .Join(TextHelper.NewLine);

            return string.Format($"OnlyDecaf:{OnlyDecaf}{TextHelper.NewLine}{serializedProcessingTypes}");
        }


        private WhereCondition GetDecafWhereCondition()
        {
            var whereCondition = new WhereCondition();

            if (OnlyDecaf)
            {
                whereCondition.WhereTrue("CoffeeIsDecaf");
            }
            return whereCondition;
        }


        private WhereCondition GetProcessingTypesWhere()
        {
            var whereCondition = new WhereCondition();
            var selectedTypes = GetSelectedTypes();

            if (selectedTypes.Any())
            {
                whereCondition.WhereIn("CoffeeProcessing", selectedTypes);
            }

            return whereCondition;

        }


        private List<string> GetSelectedTypes()
        {
            return ProcessingTypes
                .Where(x => x.IsChecked)
                .Select(x => x.Value)
                .ToList();
        }


        private IEnumerable<string> GetCoffeeProcessingTypes()
        {
            return new List<string> { "Washed", "Semiwashed", "Natural" };
        }


        private static CoffeeProductFilterCheckboxViewModel GetProductFilterCheckboxViewModel(string processingType)
        {
            return new CoffeeProductFilterCheckboxViewModel
            {
                DisplayName = ResHelper.GetString("DancingGoatMvc.Coffees." + processingType),
                Value = processingType
            };
        }
    }
}

K12WidgetDemo/DancingGoatMvc/Models/Coffees/CoffeeProductFilterCheckboxViewModel.cs
namespace DancingGoat.Models.Coffees
{
    public class CoffeeProductFilterCheckboxViewModel
    {
        public string Value { get; set; }


        public bool IsChecked { get; set; }


        public string DisplayName { get; set; }
    }
}

K12WidgetDemo/DancingGoatMvc/Models/Coffees/CoffeeViewModel.cs
using CMS.DocumentEngine.Types.DancingGoatMvc;

using DancingGoat.Models.Products;

namespace DancingGoat.Models.Coffees
{
    public class CoffeeViewModel : ITypedProductViewModel
    {
        public int Altitude { get; set; }


        public string Country { get; set; }


        public string Farm { get; set; }


        public bool IsDecaf { get; set; }


        public string Processing { get; set; }


        public string Variety { get; set; }


        public static CoffeeViewModel GetViewModel(Coffee coffee)
        {
            return new CoffeeViewModel
            {
                Altitude = coffee.Fields.Altitude,
                Country = coffee.Fields.Country,
                Farm = coffee.Fields.Farm,
                IsDecaf = coffee.Fields.IsDecaf,
                Processing = coffee.Fields.Processing,
                Variety = coffee.Fields.Variety
            };
        }
    }
}

K12WidgetDemo/DancingGoatMvc/Controllers/CoffeesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using CMS.Core;
using CMS.Ecommerce;

using DancingGoat.Models.Coffees;
using DancingGoat.Models.Products;
using DancingGoat.Repositories;
using DancingGoat.Repositories.Filters;
using DancingGoat.Services;

namespace DancingGoat.Controllers
{
    public class CoffeesController : Controller
    {
        private readonly ICoffeeRepository mCoffeeRepository;
        private readonly ICalculationService mCalculationService;


        public CoffeesController(ICoffeeRepository coffeeRepository, ICalculationService calculationService)
        {
            mCoffeeRepository = coffeeRepository;
            mCalculationService = calculationService;
        }


        // GET: Coffees
        public ActionResult Index()
        {
            var items = GetFilteredCoffees(null);
            var filter = new CoffeeFilterViewModel();
            filter.Load();

            return View(new ProductListViewModel
            {
                Filter = filter,
                Items = items
            });
        }


        // POST: Filter
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Filter(CoffeeFilterViewModel filter)
        {
            if (!Request.IsAjaxRequest())
            {
                return HttpNotFound();
            }
               
            var items = GetFilteredCoffees(filter);

            return PartialView("CoffeeList", items);
        }


        private IEnumerable<ProductListItemViewModel> GetFilteredCoffees(IRepositoryFilter filter)
        {
            var coffees = mCoffeeRepository.GetCoffees(filter);
           
            var items = coffees.Select(
                coffee => new ProductListItemViewModel(
                    coffee,
                    mCalculationService.CalculatePrice(coffee.SKU),
                    coffee.Product.PublicStatus?.PublicStatusDisplayName));
            return items;
        }
    }
}

K12WidgetDemo/DancingGoatMvc/Views/Coffees/CoffeeFilter.cshtml
@model DancingGoat.Models.Coffees.CoffeeFilterViewModel

<h4>@ResHelper.GetString("DancingGoatMvc.Coffees.CoffeeProcessing")</h4>
@Html.EditorFor(model => Model.ProcessingTypes)

<h4>@ResHelper.GetString("DancingGoatMvc.Coffees.Caffeine")</h4>
<span class="checkbox js-postback">
    @Html.CheckBoxFor(model => model.OnlyDecaf)
    @Html.LabelFor(model => model.OnlyDecaf, ResHelper.GetString("DancingGoatMvc.Coffees.OnlyDecaf"))
</span>

K12WidgetDemo/DancingGoatMvc/Views/Coffees/CoffeeList.cshtml
@using DancingGoat.Models.Products
@model IEnumerable<ProductListItemViewModel>

@if (Model.Any())
{
    foreach (var coffee in Model)
    {
        <!-- 3 products on row for large screen -->
        <div class="col-md-6 col-lg-4">
            @Html.DisplayFor(m => coffee, "ProductListItem")
        </div>
    }
}
else
{
    <span class="ContentLabel">@ResHelper.GetString("DancingGoatMvc.Coffees.NoMatchingProducts")</span>
}

K12WidgetDemo/DancingGoatMvc/Views/Coffees/Index.cshtml
@using DancingGoat.Models.Products
@model ProductListViewModel

@{
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.Coffees");
}

<div class="product-page row">
    <div class="flex">
        <aside class="col-md-4 col-lg-3 product-filter">
            @using (Html.BeginForm("Filter", "Coffees"))
            {
                @Html.AntiForgeryToken()
                @Html.Partial("CoffeeFilter", Model.Filter)
            }
        </aside>

        <div id="product-list" class="col-md-8 col-lg-9 product-list">
            @Html.Partial("CoffeeList", Model.Items)
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/formAutoPost.js")

    <script>
        $(".js-postback input:checkbox").formAutoPost({ targetContainerSelector: "#product-list" });
    </script>
}