K12WidgetDemo/DancingGoatMvc/Models/Orders/OrderAddressViewModel.cs
using System;

using CMS.Ecommerce;
using CMS.Globalization;

namespace DancingGoat.Models.Orders
{
    public class OrderAddressViewModel
    {
        public string AddressLine1 { get; set; }


        public string AddressLine2 { get; set; }


        public string AddressCity { get; set; }


        public string AddressPostalCode { get; set; }


        public string AddressState { get; set; }


        public string AddressCountry { get; set; }


        public OrderAddressViewModel()
        {
        }


        public OrderAddressViewModel(OrderAddressInfo address)
        {
            if (address == null)
            {
                return;
            }

            AddressLine1 = address.AddressLine1;
            AddressLine2 = address.AddressLine2;
            AddressCity = address.AddressCity;
            AddressPostalCode = address.AddressZip;
            AddressState = StateInfoProvider.GetStateInfo(address.AddressStateID)?.StateDisplayName ?? String.Empty;
            AddressCountry = CountryInfoProvider.GetCountryInfo(address.AddressCountryID)?.CountryDisplayName ?? String.Empty;
        }
    }
}

K12WidgetDemo/DancingGoatMvc/Models/Orders/OrderDetailViewModel.cs
using System;
using System.Collections.Generic;

using CMS.Ecommerce;

namespace DancingGoat.Models.Orders
{
    public class OrderDetailViewModel
    {
        private readonly string currencyFormatString;


        public string InvoiceNumber { get; set; }

        public decimal TotalPrice { get; set; }

        public string StatusName { get; set; }

        public OrderAddressViewModel OrderAddress { get; set; }

        public IEnumerable<OrderItemViewModel> OrderItems { get; set; }


        public OrderDetailViewModel(string currencyFormatString)
        {
            if (String.IsNullOrEmpty(currencyFormatString))
            {
                throw new ArgumentException($"{nameof(currencyFormatString)} is not defined.");
            }

            this.currencyFormatString = currencyFormatString;
        }

        public string FormatPrice(decimal price)
        {
            return String.Format(currencyFormatString, price);
        }
    }
}

K12WidgetDemo/DancingGoatMvc/Models/Orders/OrderItemViewModel.cs
namespace DancingGoat.Models.Orders
{
    public class OrderItemViewModel
    {
        public int SKUID { get; set; }

        public string SKUImagePath { get; set; }

        public string SKUName { get; set; }

        public int UnitCount { get; set; }

        public decimal UnitPrice { get; set; }

        public decimal TotalPriceInMainCurrency { get; set; }
    }
}

K12WidgetDemo/DancingGoatMvc/Models/Orders/OrdersListViewModel.cs
using System;

using CMS.Ecommerce;

namespace DancingGoat.Models.Orders
{
    public class OrdersListViewModel
    {
        public int OrderID { get; set; }


        public string OrderInvoiceNumber { get; set; }


        public DateTime OrderDate { get; set; }


        public string StatusName { get; set; }


        public string FormattedTotalPrice { get; set; }


        public OrdersListViewModel()
        {
        }


        public OrdersListViewModel(OrderInfo order)
        {
            if (order == null)
            {
                return;
            }

            OrderID = order.OrderID;
            OrderInvoiceNumber = order.OrderInvoiceNumber;
            OrderDate = order.OrderDate;
            StatusName = OrderStatusInfoProvider.GetOrderStatusInfo(order.OrderStatusID)?.StatusDisplayName;
            FormattedTotalPrice = String.Format(CurrencyInfoProvider.GetCurrencyInfo(order.OrderCurrencyID).CurrencyFormatString, order.OrderTotalPrice);
        }
    }
}

K12WidgetDemo/DancingGoatMvc/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using CMS.Base;
using CMS.Ecommerce;
using CMS.Helpers;

using DancingGoat.ActionSelectors;
using DancingGoat.Models.Checkout;
using DancingGoat.Repositories;
using DancingGoat.Services;

namespace DancingGoat.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IShoppingService mShoppingService;
        private readonly ICheckoutService mCheckoutService;
        private readonly IContactRepository mContactRepository;
        private readonly IProductRepository mProductRepository;


        public CheckoutController(IShoppingService shoppingService, IContactRepository contactRepository, IProductRepository productRepository, ICheckoutService checkoutService)
        {
            mShoppingService = shoppingService;
            mContactRepository = contactRepository;
            mCheckoutService = checkoutService;
            mProductRepository = productRepository;
        }


        public ActionResult ShoppingCart()
        {
            var viewModel = mCheckoutService.PrepareCartViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult ShoppingCartCheckout()
        {
            var cart = mShoppingService.GetCurrentShoppingCart();
            var validationErrors = ShoppingCartInfoProvider.ValidateShoppingCart(cart);

            cart.Evaluate();

            if (!validationErrors.Any())
            {
                var customer = GetCustomerOrCreateFromAuthenticatedUser();
                if (customer != null)
                {
                    mShoppingService.SetCustomer(customer);
                }

                mShoppingService.SaveCart();
                return RedirectToAction("DeliveryDetails");
            }

            // Fill model state with errors from the check result
            ProcessCheckResult(validationErrors);

            var viewModel = mCheckoutService.PrepareCartViewModel();

            return View("ShoppingCart", viewModel);
        }


        public ActionResult DeliveryDetails()
        {
            var cart = mShoppingService.GetCurrentShoppingCart();
            if (cart.IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = mCheckoutService.PrepareDeliveryDetailsViewModel();

            return View(viewModel);
        }


        public ActionResult PreviewAndPay()
        {
            if (mShoppingService.GetCurrentShoppingCart().IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = mCheckoutService.PreparePreviewViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreviewAndPay(PreviewViewModel model)
        {
            var cart = mShoppingService.GetCurrentShoppingCart();

            if (cart.IsEmpty)
            {
                ModelState.AddModelError("cart.empty", ResHelper.GetString("DancingGoatMvc.Checkout.EmptyCartError"));

                var viewModel = mCheckoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            if (!mCheckoutService.IsPaymentMethodValid(model.PaymentMethod.PaymentMethodID))
            {
                ModelState.AddModelError("PaymentMethod.PaymentMethodID", ResHelper.GetString("DancingGoatMvc.Payment.PaymentMethodRequired"));
            }
            else
            {
                mShoppingService.SetPaymentOption(model.PaymentMethod.PaymentMethodID);
            }

            var validator = new CreateOrderValidator(cart);

            if (!validator.Validate())
            {
                ProcessCheckResult(validator.Errors);
            }

            if (!ModelState.IsValid)
            {
                var viewModel = mCheckoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            try
            {
                mShoppingService.CreateOrder();
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("cart.createordererror", ex.Message);
                var viewModel = mCheckoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            return RedirectToAction("ThankYou");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult DeliveryDetails(DeliveryDetailsViewModel model)
        {
            // Check the selected shipping option
            bool isShippingNeeded = mShoppingService.GetCurrentShoppingCart().IsShippingNeeded;
            if (isShippingNeeded && !mCheckoutService.IsShippingOptionValid(model.ShippingOption.ShippingOptionID))
            {
                ModelState.AddModelError("ShippingOption.ShippingOptionID", ResHelper.GetString("DancingGoatMvc.Shipping.ShippingOptionRequired"));
            }

            // Check if the billing address's country and state are valid
            var countryStateViewModel = model.BillingAddress.BillingAddressCountryStateSelector;
            if (!mCheckoutService.IsCountryValid(countryStateViewModel.CountryID))
            {
                countryStateViewModel.CountryID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.CountryID", ResHelper.GetString("DancingGoatMvc.Address.CountryIsRequired"));
            }
            else if (!mCheckoutService.IsStateValid(countryStateViewModel.CountryID, countryStateViewModel.StateID))
            {
                countryStateViewModel.StateID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.StateID", ResHelper.GetString("DancingGoatMvc.Address.StateIsRequired"));
            }

            if (!ModelState.IsValid)
            {
                var viewModel = mCheckoutService.PrepareDeliveryDetailsViewModel(model.Customer, model.BillingAddress, model.ShippingOption);

                return View(viewModel);
            }

            var customer = GetCustomerOrCreateFromAuthenticatedUser() ?? new CustomerInfo();
            bool emailCanBeChanged = !User.Identity.IsAuthenticated || string.IsNullOrWhiteSpace(customer.CustomerEmail);
            model.Customer.ApplyToCustomer(customer, emailCanBeChanged);
            mShoppingService.SetCustomer(customer);

            var modelAddressID = model.BillingAddress.BillingAddressSelector?.AddressID ?? 0;
            var billingAddress = mCheckoutService.GetAddress(modelAddressID) ?? new AddressInfo();

            model.BillingAddress.ApplyTo(billingAddress);
            billingAddress.AddressPersonalName = $"{customer.CustomerFirstName} {customer.CustomerLastName}";

            mShoppingService.SetBillingAddress(billingAddress);
            mShoppingService.SetShippingOption(model.ShippingOption?.ShippingOptionID ?? 0);

            return RedirectToAction("PreviewAndPay");
        }


        public ActionResult ThankYou()
        {
            var companyContact = mContactRepository.GetCompanyContact();

            var viewModel = new ThankYouViewModel
            {
                Phone = companyContact.Phone
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult AddItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                mShoppingService.AddItemToCart(item.SKUID, item.Units);
            }

            return RedirectToAction("ShoppingCart");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult UpdateItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                mShoppingService.UpdateItemQuantity(item.ID, item.Units);
            }
            else
            {
                // Add an item error and save ViewData so that the ShoppingCart action can show validation errors
                var key = item.ID.ToString();
                ModelState.Add(key, ModelState["Units"]);
            }

            var cartViewModel = mCheckoutService.PrepareCartViewModel();
            return View("ShoppingCart", cartViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult RemoveItem(CartItemUpdateModel item)
        {
            mShoppingService.RemoveItemFromCart(item.ID);

            var cartViewModel = mCheckoutService.PrepareCartViewModel();
            return View("ShoppingCart", cartViewModel);
        }


        [HttpPost]
        public JsonResult CustomerAddress(int addressID)
        {
            var address = mCheckoutService.GetCustomerAddress(addressID); 

            if (address == null)
            {
                return null;
            }

            var responseModel = new
            {
                Line1 = address.AddressLine1,
                Line2 = address.AddressLine2,
                City = address.AddressCity,
                PostalCode = address.AddressZip,
                CountryID = address.AddressCountryID,
                StateID = address.AddressStateID,
                PersonalName = address.AddressPersonalName
            };

            return Json(responseModel);
        }


        public ActionResult ItemDetail(int skuId)
        {
            var product = mProductRepository.GetProductForSKU(skuId);

K12WidgetDemo/DancingGoatMvc/Controllers/OrdersController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

using Kentico.Membership;

using DancingGoat.Models.Orders;
using DancingGoat.Repositories;

using CMS.Ecommerce;

namespace DancingGoat.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderRepository mOrderRepository;
        private readonly IShoppingService mShoppingService;


        private CustomerInfo CurrentCustomer => mShoppingService.GetCurrentCustomer();


        public OrdersController(IOrderRepository orderRepository, IShoppingService shoppingService)
        {
            mOrderRepository = orderRepository;
            mShoppingService = shoppingService;
        }


        // GET: Orders
        [Authorize]
        public ActionResult Index()
        {
            var currentCustomer = mShoppingService.GetCurrentCustomer();
            var orders = currentCustomer != null
                ? mOrderRepository.GetByCustomerId(currentCustomer.CustomerID).Select(order => new OrdersListViewModel(order))
                : Enumerable.Empty<OrdersListViewModel>();

            return View(orders);
        }


        // GET: Orders/OrderDetail
        [Authorize]
        public ActionResult OrderDetail(int? orderID)
        {
            if (orderID == null)
            {
                return RedirectToAction("Index");
            }

            var order = mOrderRepository.GetById(orderID.Value);

            if ((order == null) || (order.OrderCustomerID != CurrentCustomer?.CustomerID))
            {
                return RedirectToAction("NotFound", "HttpErrors");
            }

            var currency = CurrencyInfoProvider.GetCurrencyInfo(order.OrderCurrencyID);

            return View(new OrderDetailViewModel(currency.CurrencyFormatString)
            {
                InvoiceNumber = order.OrderInvoiceNumber,
                TotalPrice = order.OrderTotalPrice,
                StatusName = OrderStatusInfoProvider.GetOrderStatusInfo(order.OrderStatusID)?.StatusDisplayName,
                OrderAddress = new OrderAddressViewModel(order.OrderBillingAddress),
                OrderItems = OrderItemInfoProvider.GetOrderItems(order.OrderID).Select(orderItem =>
                {
                    return new OrderItemViewModel
                    {
                        SKUID = orderItem.OrderItemSKUID,
                        SKUName = orderItem.OrderItemSKUName,
                        SKUImagePath = orderItem.OrderItemSKU.SKUImagePath,
                        TotalPriceInMainCurrency = orderItem.OrderItemTotalPriceInMainCurrency,
                        UnitCount = orderItem.OrderItemUnitCount,
                        UnitPrice = orderItem.OrderItemUnitPrice
                    };
                })
            });
        }
    }
}

K12WidgetDemo/DancingGoatMvc/Views/Orders/Index.cshtml
@model IEnumerable<DancingGoat.Models.Orders.OrdersListViewModel>

@{
    ViewBag.Title = @ResHelper.GetString("DancingGoatMvc.YourOrders.Orders");
}

<a href="@Url.Action("YourAccount", "Account")">&larr; @ResHelper.GetString("DancingGoatMvc.YourAccount.Back")</a>


<h2>@ResHelper.GetString("DancingGoatMvc.YourOrders.Orders")</h2>

<div id="no-more-tables">
    <table class="orders-table">
        <thead>
            <tr>
                <th class="column-id">@ResHelper.GetString("DancingGoatMvc.YourOrders.OrderId")</th>
                <th class="column-date">@ResHelper.GetString("DancingGoatMvc.YourOrders.Date")</th>
                <th class="column-status">@ResHelper.GetString("DancingGoatMvc.YourOrders.Status")</th>
                <th class="column-total">@ResHelper.GetString("DancingGoatMvc.YourOrders.Total")</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td class="column-id">
                        <span class="strong">@order.OrderInvoiceNumber</span>
                        @Html.ActionLink(ResHelper.GetString("DancingGoatMvc.YourOrders.OrderDetail"), "OrderDetail", new { orderID = order.OrderID }, new { @class = "btn btn-terciary" })
                    </td>
                    <td class="column-date">@order.OrderDate</td>
                    <td class="column-status">
                        <span class="status">
                            @ResHelper.LocalizeString(order.StatusName)
                        </span>
                    </td>
                    <td class="column-total">@order.FormattedTotalPrice</td>
                </tr>
            }
        </tbody>
    </table>
</div>

K12WidgetDemo/DancingGoatMvc/Views/Orders/OrderDetail.cshtml
@model DancingGoat.Models.Orders.OrderDetailViewModel

@{
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.YourOrders.OrderDetail");
}

<a href="@Url.Action("Index", "Orders")">&larr; @ResHelper.GetString("DancingGoatMvc.YourOrders.OrderDetail.Back")</a>
<h2>
    @ResHelper.GetString("DancingGoatMvc.YourOrders.OrderDetail")
    @Model.InvoiceNumber - @ResHelper.LocalizeString(Model.StatusName)
</h2>
<hr />
<div>
    <div class="row">
        <div class="col-md-6">
            <h3>@ResHelper.GetString("DancingGoatMvc.Checkout.BillingDetails")</h3>
            @Html.DisplayFor(m => m.OrderAddress)
        </div>
        <div class="col-md-6">
            <h3>@ResHelper.GetString("DancingGoatMvc.Checkout.ShippingDetails")</h3>
            @Html.DisplayFor(m => m.OrderAddress)
        </div>
    </div>
    <div>
        <h4>@ResHelper.GetString("DancingGoatMvc.YourOrders.OrderDetail.Items")</h4>
        <hr />
        @foreach (var orderItem in Model.OrderItems)
        {
            <div class="row order-item">
                <div class="col-md-10">
                    <div class="order-item-image">
                        <a href="@Url.Action("ItemDetail", "Checkout", new {skuId = orderItem.SKUID})">
                            @Html.Image(@orderItem.SKUImagePath, @orderItem.SKUName, null, SizeConstraint.MaxWidthOrHeight(70))
                        </a>
                    </div>
                    <div class="order-item-info">
                        @Html.ActionLink(orderItem.SKUName, "ItemDetail", "Checkout", new {skuId = orderItem.SKUID }, null)
                    </div>
                    <div class="order-item-amount">
                        <div>
                            <span class="strong">Qty: </span>
                            <span>@orderItem.UnitCount</span>
                        </div>
                        <div>
                            <span class="strong">Unit price: </span>
                            <span>@Model.FormatPrice(orderItem.UnitPrice)</span>
                        </div>

                    </div>

                    @Html.ValidationMessage(orderItem.UnitPrice.ToString(), new {@class = "red"})

                </div>
                <div class="col-md-2 order-item-subtotal">
                    <span>@Model.FormatPrice(orderItem.TotalPriceInMainCurrency)</span>
                </div>
            </div>
            <hr />
        }
        <div class="order-total-price">
            <div>
                <span class="strong">@ResHelper.GetString("DancingGoatMvc.YourOrders.OrderDetail.Total")</span>
                <span class="total-price">@Model.FormatPrice(Model.TotalPrice)</span>
            </div>
        </div>

    </div>
</div>